#!/bin/bash

pushd $HOME/repository/ > /dev/null

# future additions:
# blazeterm scripts
# flushback scripts
# dropfetch
# fontflow
# path to misc scripts

cloc                                    \
--force-lang="C,h"                      \
bash-collection/                        \
blazeterm/src/                          \
blazeterm/include/                      \
cpong/src/                              \
cpong/include/                          \
cpong/clean.ps1                         \
cpong/run.ps1                           \
cpong/debug.ps1                         \
flushback/src/                          \
flushback/include/                      \
gitfluss/src/                           \
gitfluss/include/                       \
gitfluss/clean                          \
gitfluss/clean.ps1                      \
gitfluss/debug.ps1                      \
gitfluss/profile                        \
gitfluss/run                            \
gitfluss/run.ps1                        \
imgsurf/src/                            \
imgsurf/include/                        \
imgsurf/clean                           \
imgsurf/clean.ps1                       \
imgsurf/run                             \
imgsurf/run.ps1                         \
islescape/src/                          \
islescape/include/                      \
islescape/clean                         \
islescape/clean.ps1                     \
islescape/debug                         \
islescape/debug.ps1                     \
islescape/package                       \
islescape/package.ps1                   \
islescape/run                           \
islescape/run.ps1                       \
marino/src/                             \
marino/include/                         \
marino/clean                            \
marino/run                              \
puddle/src/                             \
puddle/include/                         \
puddle/clean                            \
puddle/clean.ps1                        \
puddle/run                              \
puddle/run.ps1                          \
pwsh-collection                         \
river2D/src/                            \
river2D/include/                        \
river2D/clean                           \
river2D/clean.ps1                       \
river2D/run                             \
river2D/run.ps1                         \
river2D_mapedit/src/                    \
river2D_mapedit/include/                \
river2D_mapedit/clean                   \
river2D_mapedit/clean.ps1               \
river2D_mapedit/debug                   \
river2D_mapedit/debug.ps1               \
river2D_mapedit/package                 \
river2D_mapedit/package.ps1             \
river2D_mapedit/profile                 \
river2D_mapedit/run                     \
river2D_mapedit/run.ps1                 \
river3D/src/                            \
river3D/include/                        \
river3D/clean.ps1                       \
river3D/debug.ps1                       \
river3D/run                             \
river3D/setup.ps1                       \
river3D/shader_comp.ps1                 \
snek/src/                               \
snek/include/                           \
snek/clean.ps1                          \
snek/disassemble.ps1                    \
snek/run.ps1                            \

popd > /dev/null
