#!/bin/bash

pushd $HOME/repository/ > /dev/null

cloc                            \
--force-lang="C,h"              \
imgsurf/src/                    \
imgsurf/include/                \
imgsurf/run                     \
river2D/src/                    \
river2D/include/                \
river2D/run                     \
river3D/src/                    \
river3D/include/                \
river3D/run                     \
river2D_mapedit/src/            \
river2D_mapedit/include/        \
river2D_mapedit/run             \
river2D_mapedit/package         \
islescape/src/                  \
islescape/include/              \
islescape/run                   \
islescape/package               \
marino/src/                     \
marino/include/                 \
flushback/src/                  \
flushback/include/              \
puddle/src/                     \
puddle/include/                 \
puddle/run                      \
gitfluss/src/                   \
gitfluss/include/               \
bash-collection/                \
PWSH-Collection/                \
CPong/src/                      \
CPong/include/                  \
Snek/src/                       \
Snek/include/                   \
UNI/                            \

popd > /dev/null
