#!/bin/bash

pushd $HOME/repository/ > /dev/null

cloc                            \
imgsurf/src/                    \
imgsurf/include/                \
river2D/src/                    \
river2D/include/                \
river3D/src/                    \
river3D/include/                \
river2D_mapedit/src/            \
river2D_mapedit/include/        \
islescape/src/                  \
islescape/include/              \
marino/src/                     \
marino/include/                 \
flushback/src/                  \
flushback/include/              \
puddle/src/                     \
puddle/include/                 \
gitfluss/src/                   \
gitfluss/include/               \
bash-collection/                \
PWSH-Collection/                \
CPong/src/                      \
CPong/include/                  \
Snek/src/                       \
Snek/include/                   \
UNI/                            \

popd > /dev/null
