#!/bin/bash

# TODO: back up OBS settings & such
# TODO: don't back up writing's git directory, but every subfolder besides that. lol

pkglist="           \
cloc                \
picom               \
lazygit             \
librewolf-bin       \
wezterm-nightly-bin \
"

function config_setup()
{
    # TODO: assume I'm setting up an arch machine
    echo -e "\n\033[1;35minitiating full setup.\033[0m"
    echo -e "\ndownloading yay..."

    # TODO: install yay

    echo -e "\ndownloading full list of packages..."
    yay -Sy $pkglist

    # TODO: add all relevant packages here
    echo -e "\n\033[1;32mall done!\033[0m\n"
}

function config_pull()
{
    echo -e "\n\033[1;35mpulling config files.\033[0m"
    # TODO: pull every relevant config from the repo,
    # keep track of how many files were updated,
    # give summary of which
    echo -e "\n\033[1;32mall done!\033[0m\n"
}

function move_to_smb_recurse()
{
    if [[ -f "$1" ]]
    then
        echo "$1"
        #TODO: move file to smb path counterpart, figure out pwd
    else
    if [[ -d "$1" ]]
    then
        pushd "$1" > /dev/null

        for item in *
        do
            move_to_smb_recurse "$item"
        done

        popd > /dev/null
    fi
    fi
}

function config_push()
{
    echo -e "\n\033[1;35mbacking up writings...\033[0m"

    # TODO: back up only .typ / .txt / .md files, show each individually in output!
    # instead of:
    cp "$HOME/writing/" "$HOME/smb/" -r

    move_to_smb_recurse "$HOME/writing/"

    echo -e "\n\033[1;35mpushing config files.\033[0m"

    mkdir $HOME/smb/Backups/nitrogen/ 2> /dev/null
    echo -e "\n\033[1;35mbacking up nitrogen configs...\033[0m"

    pushd $HOME/.config/nitrogen/ > /dev/null
    for config in profile*
    do
        if [[ ! -f $config ]]
        then
            continue;
        fi

        cp $config $HOME/smb/Backups/nitrogen/$(basename $config)
        echo -e "backed up $config."
    done

    pushd $HOME/.config/nitrogen_backup/ > /dev/null
    for config in profile*
    do
        if [[ ! -f $config ]]
        then
            continue;
        fi

        cp $config $HOME/smb/Backups/nitrogen/$(basename $config)
        echo -e "backed up $config."
    done

    pushd $HOME/.config/nitrogen_backup_/ > /dev/null
    for config in profile*
    do
        if [[ ! -f $config ]]
        then
            continue;
        fi

        cp $config $HOME/smb/Backups/nitrogen/$(basename $config)
        echo -e "backed up $config."
    done

    popd > /dev/null
    popd > /dev/null
    popd > /dev/null

    mkdir $HOME/smb/Backups/fastfetch/ 2> /dev/null
    echo -e "\n\033[1;35mbacking up fastfetch configs...\033[0m"

    pushd $HOME/.config/fastfetch/ > /dev/null
    for config in *.jsonc
    do
        if [[ ! -f $config ]] || [[ $config = "config.jsonc" ]]
        then
            continue;
        fi

        cp $config $HOME/smb/Backups/fastfetch/$(basename $config)
        echo -e "backed up $config."
    done

    pushd $HOME/.config/fastfetch_backup/ > /dev/null
    for config in *.jsonc
    do
        if [[ ! -f $config ]] || [[ $config = "config.jsonc" ]]
        then
            continue;
        fi

        cp $config $HOME/smb/Backups/fastfetch/$(basename $config)
        echo -e "backed up $config."
    done

    pushd $HOME/.config/fastfetch_backup_/ > /dev/null
    for config in *.jsonc
    do
        if [[ ! -f $config ]] || [[ $config = "config.jsonc" ]]
        then
            continue;
        fi

        cp $config $HOME/smb/Backups/fastfetch/$(basename $config)
        echo -e "backed up $config."
    done

    popd > /dev/null
    popd > /dev/null
    popd > /dev/null

    echo -e "\n\033[1;35mbacking up configuration files...\033[0m"

    boomer=$HOME/.config/boomer/config
    if [[ -f $boomer ]]
    then
        cp $boomer $HOME/repository/dotfiles/boomer/config
        echo -e "backed up $boomer."
    else
        echo -e "WARN: no config found in $boomer."
    fi

    i3=$HOME/.config/i3/config
    if [[ -f $i3 ]]
    then
        cp $i3 $HOME/repository/dotfiles/i3/i3/config
        echo -e "backed up $i3."
    else
        echo -e "WARN: no config found in $i3."
    fi

    i3status=$HOME/.config/i3status/config
    if [[ -f $i3status ]]
    then
        cp $i3status $HOME/repository/dotfiles/i3/i3status/config
        echo -e "backed up $i3status."
    else
        echo -e "WARN: no config found in $i3status."
    fi

    mangohudcustom=$HOME/.config/MangoHud/custom.conf
    if [[ -f $mangohudcustom ]]
    then
        cp $mangohudcustom $HOME/repository/dotfiles/MangoHud/custom.conf
        echo -e "backed up $mangohudcustom."
    else
        echo -e "WARN: no config found in $mangohudcustom."
    fi

    mangohuddefault=$HOME/.config/MangoHud/MangoHud.conf
    if [[ -f $mangohuddefault ]]
    then
        cp $mangohuddefault $HOME/repository/dotfiles/MangoHud/MangoHud.conf
        echo -e "backed up $mangohuddefault."
    else
        echo -e "WARN: no config found in $mangohuddefault."
    fi

    mpv=$HOME/.config/mpv/mpv.conf
    if [[ -f $mpv ]]
    then
        cp $mpv $HOME/repository/dotfiles/mpv/mpv.conf
        echo -e "backed up $mpv."
    else
        echo -e "WARN: no config found in $mpv."
    fi

    nviminit=$HOME/.config/nvim/init.lua
    if [[ -f $nviminit ]]
    then
        cp $nviminit $HOME/repository/dotfiles/nvim/init.lua
        echo -e "backed up $nviminit."
    else
        echo -e "WARN: no config found in $nviminit."
    fi

    nvimoptions=$HOME/.config/nvim/lua/nvimoptions.lua
    if [[ -f $nvimoptions ]]
    then
        cp $nvimoptions $HOME/repository/dotfiles/nvim/lua/nvimoptions.lua
        echo -e "backed up $nvimoptions."
    else
        echo -e "WARN: no config found in $nvimoptions."
    fi

    lspconfig=$HOME/.config/nvim/lua/lspconfig.lua
    if [[ -f $lspconfig ]]
    then
        cp $lspconfig $HOME/repository/dotfiles/nvim/lua/lspconfig.lua
        echo -e "backed up $lspconfig."
    else
        echo -e "WARN: no config found in $lspconfig."
    fi

    pushd "$HOME/.config/nvim/lua/plugins" > /dev/null

    for plugin in *.lua
    do
        if [[ ! -f $plugin ]]
        then
            echo -e "WARN: no configs found in $(pwd)."
        fi

        cp $plugin $HOME/repository/dotfiles/nvim/lua/plugins/
        echo -e "backed up $HOME/.config/nvim/lua/plugins/$plugin."
    done

    popd > /dev/null

    picom=$HOME/.config/picom/picom.conf
    if [[ -f $picom ]]
    then
        cp $picom $HOME/repository/dotfiles/picom/picom.conf
        echo -e "backed up $picom."
    else
        echo -e "WARN: no config found in $picom."
    fi

    wezterm=$HOME/.config/wezterm/wezterm.lua
    if [[ -f $wezterm ]]
    then
        cp $wezterm $HOME/repository/dotfiles/wezterm/wezterm.lua
        echo -e "backed up $wezterm."
    else
        echo -e "WARN: no config found in $wezterm."
    fi

    bashrc=$HOME/.bashrc
    if [[ -f $bashrc ]]
    then
        cp $bashrc $HOME/repository/dotfiles/x11/.bashrc
        echo -e "backed up $bashrc."
    else
        echo -e "WARN: no config found in $bashrc."
    fi

    bashprofile=$HOME/.bash_profile
    if [[ -f $bashprofile ]]
    then
        cp $bashprofile $HOME/repository/dotfiles/x11/.bash_profile
        echo -e "backed up $bashprofile."
    else
        echo -e "WARN: no config found in $bashprofile."
    fi

    xinitrc=$HOME/.xinitrc
    if [[ -f $xinitrc ]]
    then
        cp $xinitrc $HOME/repository/dotfiles/x11/.xinitrc
        echo -e "backed up $xinitrc."
    else
        echo -e "WARN: no config found in $xinitrc."
    fi

    xresources=$HOME/.Xresources
    if [[ -f $xresources ]]
    then
        cp $xresources $HOME/repository/dotfiles/x11/.Xresources
        echo -e "backed up $xresources."
    else
        echo -e "WARN: no config found in $xresources."
    fi

    # TODO: display lazygit if there is a diff

    echo -e "\n\033[1;32mall done!\033[0m\n"
}

function config_clean
{
    yay -Sc
    echo -e "\n\033[1;32mall done!\033[0m\n"
}

if [[ $1 = "setup" ]]; then
    config_setup
    config_pull

else if [[ $1 = "pull" ]]; then
    config_pull

else if [[ $1 = "push" ]]; then
    config_push

else if [[ $1 = "clean" ]]; then
    config_clean

else
    echo "no operation selected."
fi
fi
fi
fi
