#!/bin/bash

wordcount=0
filecount=0

function add_files()
{
    if [[ -f "$1" ]]
    then
        if [[ "$1" =~ \.(typ|md|txt)$ ]]
        then
            counts=$(wc "$1" -w | grep -o -E '[0-9]+')
            for current in $counts
            do
                wordcount=$((wordcount + current))
                filecount=$((filecount + 1))
                break;
            done
        fi

        if [[ "$1" =~ \.doc$ ]]
        then
            catdoc "$1" > "${1%.doc}.typ"
            echo "converted .doc -> .typ: $1"
            rm "$1"
            wc "${1%.doc}.typ" -w
        fi

        if [[ "$1" =~ \.docx$ ]]
        then
            docx2txt "$1" "${1%.docx}.typ"
            echo "converted .docx -> .typ: $1"
            rm "$1"
            wc "${1%.docx}.typ" -w
        fi
    fi

    if [[ -d "$1" ]]
    then
        pushd "$1" > /dev/null

        for item in *
        do
            add_files "$item"
        done

        popd > /dev/null
    fi
}

add_files "$HOME/writing/"

pages=$((wordcount / 250))
books=$((pages / 300))

echo "----------------------------------------------------"
echo "$wordcount words in $filecount files."
echo "$pages total pages in $books average-length novels."
# TODO: take every file that's estimated to be above 100 pages, then list them below and say how many words, pages they would be!
# echo "$largest words in the largest file."
# echo "$largestpages pages in the largest file."
echo "----------------------------------------------------"
