#!/bin/bash

if [[ $1 = "4mon" ]]
then
    xrandr                                                                          \
        --fb 7840x2880                                                              \
        --output DP-1   --mode "3840x2160_146" --pos 2560x480                \
        --output DP-2   --mode "2560x1440_75"  --pos 0x0                     \
        --output HDMI-1 --mode "2560x1440_75"  --pos 6400x0 --rotate right   \
        --output HDMI-2 --mode "2560x1440_75"  --pos 0x1440
else
if [[ $1 = "gaming" ]]
then
    xrandr                                                                          \
        --fb 5280x2560                                                              \
        --output DP-1   --mode "3840x2160_240" --pos 0x0                     \
        --output DP-2   --off                                                \
        --output HDMI-1 --mode "2560x1440_75"  --pos 3840x0 --rotate right   \
        --output HDMI-2 --off
else
    echo -e "\033[31;1mERROR: unknown displaymode '$1'.\033[0m"
    exit 1;
fi
fi

echo $1 > $HOME/.displaymode
nitrogen --restore 2>/dev/null &
