#!/bin/bash

configFolder="$HOME/.config/fastfetch/"
configFolder=$(realpath $configFolder)

#WIP: finish these
#   delete -name-
#   save   -name-

if [[ $1 = "list" ]]
then
    for name in $(find $configFolder)
    do
        name="${name##*/}"
        echo "${name%.jsonc}"
    done

elif [[ $1 = "edit" ]]
then
    if [[ $2 = '' ]]
    then
        echo "editing current configuration..."
        nvim "$configFolder/config.jsonc"
    else
        echo "editing '$2'"
        nvim "$configFolder/$2.jsonc"
    fi

elif [[ $1 = "delete" ]]
then
    pushd $configFolder > /dev/null
    if [[ -f $2.jsonc ]]
    then
        rm $2.jsonc
        echo "deleted configuration '$2.jsonc'."
    else
        echo "NOTE: configuration named '$2' does not exist."
    fi
    popd > /dev/null

elif [[ $1 = "save" ]]
then
    pushd $configFolder > /dev/null
    cp "config.jsonc" $2.jsonc
    echo "saved current config as $2.jsonc."
    popd > /dev/null

else
    if [[ $1 != '' ]]
    then
        pushd $configFolder > /dev/null
        if [[ -f $1.jsonc ]]
        then
            cp "$1.jsonc" "config.jsonc"
        else
            echo "NOTE: configuration named '$1' does not exist."
        fi
        popd > /dev/null
    fi

    fastfetch
fi
