#!/bin/bash

configFolder="$HOME/.config/fastfetch/"
configFolder=$(realpath $configFolder)

if [[ $1 = "list" ]]
then
    for name in $(ls $configFolder -I config.jsonc)
    do
        name="${name##*/}"
        echo "${name%.jsonc}"
    done

elif [[ $1 = "edit" ]]
then
    if [[ $2 = '' ]]
    then
        echo "editing current configuration..."
        nvim "$configFolder/config.jsonc"
    else
        echo "editing '$2'"
        nvim "$configFolder/$2.jsonc"
    fi

elif [[ $1 = "delete" ]]
then
    pushd $configFolder > /dev/null

    if [[ -f $2.jsonc ]]
    then
        rm $2.jsonc
        echo "deleted configuration '$2.jsonc'."
    else
        echo -e "\033[31;1;1mERROR: configuration named '$2' does not exist.\033[0m\n"
        exit 1;
    fi

    popd > /dev/null

elif [[ $1 = "save" ]]
then
    pushd $configFolder > /dev/null

    if [[ $2 = "" ]]
    then
        echo "can't save to a theme with no name."
    else
        cp "config.jsonc" $2.jsonc
        echo "saved current config as $2.jsonc."
    fi

    popd > /dev/null

else
    if [[ $1 != '' ]]
    then
        pushd $configFolder > /dev/null

        if [[ $1 = "random" ]]
        then
            ffconf=$(ls "$HOME/.config/fastfetch/" -I config.jsonc | shuf -n 1)
        else
            if [[ -f $1.jsonc ]]
            then
                ffconf="$1.jsonc"
            else
                echo -e "\033[31;1;1mERROR: configuration named '$1' does not exist.\033[0m\n"
                exit 1;
            fi
        fi

        cp $ffconf "config.jsonc"
        popd > /dev/null
    fi

    fastfetch
fi
