#!/bin/bash

if [[ ! pgrep -f xidlehook ]]
then
    xidlehook --not-when-audio --not-when-fullscreen                                                                                                       \
        --timer 60  'xrandr --output DP-2 --brightness .5 --output HDMI-1 --brightness .5 --output HDMI-2 --brightness .5 --output DP-1 --brightness .5 '  \
                    'xrandr --output DP-2 --brightness 1  --output HDMI-1 --brightness .8 --output HDMI-2 --brightness .8 --output DP-1 --brightness .8 '  \
        --timer 60  'xrandr --output DP-2 --brightness .1 --output HDMI-1 --brightness .1 --output HDMI-2 --brightness .1 --output DP-1 --brightness .1 '  \
                    'xrandr --output DP-2 --brightness 1  --output HDMI-1 --brightness .8 --output HDMI-2 --brightness .8 --output DP-1 --brightness .8 '  \
        --timer 300 'systemctl sleep-then-hibernate' '' &
fi
