#!/bin/bash

if [[ ! $(pgrep -f xidlehook) ]]
then
    xidlehook                                                                                                                                               \
        --not-when-fullscreen                                                                                                                               \
        --timer 300 'xrandr --output DP-2 --brightness .5 --output HDMI-1 --brightness .5 --output HDMI-2 --brightness .5 --output DP-1 --brightness .5 '   \
                    'xrandr --output DP-2 --brightness 1  --output HDMI-1 --brightness 1  --output HDMI-2 --brightness 1  --output DP-1 --brightness 1  '   \
        --timer 100 'xrandr --output DP-2 --brightness 0  --output HDMI-1 --brightness 0  --output HDMI-2 --brightness 0  --output DP-1 --brightness 0  '   \
                    'xrandr --output DP-2 --brightness 1  --output HDMI-1 --brightness 1  --output HDMI-2 --brightness 1  --output DP-1 --brightness 1  '   \
        --timer 100 'systemctl sleep-then-hibernate' ''
fi
