#!/bin/bash

declare -A modmap

mergecount=0
uniquemods=0
jsoncount=0

for mcm in *.json
do
    index=${mcm:0:4}
    modname=${mcm:4}

    echo "$index$modname"

    uniqueindex="$(printf "%04d" $uniquemods)"
    if [[ $index != $uniqueindex ]]
    then
        echo -e "\033[33;1;3m$index$modname -> $uniqueindex$modname\033[0;0m"
        mv "./$mcm" "./$uniqueindex$modname"
    fi

    if [[ ${modmap[$modname]} = "" ]]
    then
        modmap[$modname]=$uniqueindex
        uniquemods="$(($uniquemods + 1))"
    else
        echo -e "\033[31;1;1mduplicate MCM: ${modname:1}, first index ${modmap[$modname]}\033[0;0m"

        mod1="${modmap[$modname]}$modname"
        mod2="$uniqueindex$modname"

        cp "$mod1" "./temp"

        jq -s '.[0] + .[1]' "./$mod1" "$mod2" > "./temp"

        if [[ $? != 0 ]]
        then
            echo -e "\033[31;1;1mERROR: jq failed.\033[0;0m"
            exit -1;
        fi

        mv "./temp" "$mod1"
        rm "./$mod2"
        echo -e "\033[33;1;3mmerged $mod2 into $mod1!\033[0;0m"

        mergecount="$(($mergecount + 1))"
    fi

    jsoncount="$(($jsoncount + 1))"
done

if [[ -f "./temp" ]]
then
    rm "./temp"
fi

echo -e "\033[32;1;1mreduction: $jsoncount -> $uniquemods"
echo -e "merged $mergecount files!\033[0;0m"
