#!/bin/bash

pushd $HOME/.config/nitrogen > /dev/null

if [[ $1 = "random" ]]
then
    theme=$(ls -I bg-saved.cfg -I nitrogen.cfg | shuf -n 1)
else
if [[ $1 = "list" ]]
then
    for name in $(ls -I bg-saved.cfg -I nitrogen.cfg)
    do
        echo "${name#profile-}"
    done
    popd > /dev/null
    exit 0;
else
    theme="profile-$1"

    if [[ ! -f $theme ]]
    then
        echo -e "\n\033[31;1;1ma profile of name $theme does not exist.\033[0m\n"
        popd > /dev/null
        exit 1;
    fi
fi
fi

cp $theme bg-saved.cfg
nitrogen --restore 2> /dev/null
popd > /dev/null
