#!/bin/bash

if [[ $1 = "random" ]]
then
    theme=$(ls "$HOME/.config/nitrogen/" -I bg-saved.cfg -I nitrogen.cfg | shuf -n 1)
else
    theme="$HOME/.config/nitrogen/profile-$1"
fi

pushd $HOME/.config/nitrogen > /dev/null

cp $theme bg-saved.cfg
nitrogen --restore 2> /dev/null

popd > /dev/null
