#!/bin/bash

pushd $HOME/.config/nitrogen > /dev/null

if [[ $1 = "random" ]]
then
    theme=$(ls -I bg-saved.cfg -I nitrogen.cfg | shuf -n 1)
else
if [[ $1 = "save" ]]
then
    if [[ $2 = "" ]]
    then
        echo -e "\n\033[31;1;1ma no name specified to save profile as.\033[0m\n"
        exit 1;
    fi
    cp bg-saved.cfg profile-$2
    echo -e "saved current configuration as profile-$2."
    popd > /dev/null
    exit 0;
else
if [[ $1 = "delete" ]]
then
    if [[ $2 = "" ]]
    then
        echo -e "\n\033[31;1;1ma no profile to delete specified.\033[0m\n"
        exit 1;
    else
    if [[ ! -f "profile-$2" ]]
    then
        echo -e "\n\033[31;1;1ma profile-$2 does not exist, can't delete.\033[0m\n"
        exit 1;
    fi
    fi

    rm profile-$2
    echo -e "successfully deleted configuration profile-$2."
    popd > /dev/null
    exit 0;
else
if [[ $1 = "list" ]]
then
    for name in $(ls -I bg-saved.cfg -I nitrogen.cfg)
    do
        echo "${name#profile-}"
    done
    popd > /dev/null
    exit 0;
else
    theme="profile-$1"

    if [[ ! -f $theme ]] && [[ -f "$theme-0" ]]
    then
        count=0

        for curr in $theme-*
        do
            count=$((count + 1))
        done

        final=$(seq $count | shuf -n 1)
        theme="$theme-$((final - 1))"

    else
        if [[ ! -f $theme ]]
        then
            echo -e "\n\033[31;1;1ma profile of name $theme does not exist.\033[0m\n"
            popd > /dev/null
            exit 1;
        fi
    fi
fi
fi
fi
fi

cp $theme bg-saved.cfg
nitrogen --restore 2> /dev/null
popd > /dev/null
