#!/bin/bash

function set_streamer_mode()
{
    pushd ~/.config/nitrogen/ > /dev/null

    for config in profile*
    do
        if [[ ! -f $config ]]
        then
            continue;
        fi

        rm $config
    done
    popd > /dev/null

    pushd ~/.config/nitrogen_backup_/ > /dev/null
    dir="$HOME/.config/nitrogen/"

    if [[ ! -d $dir ]]
    then
        mkdir $dir > /dev/null
    fi

    for config in profile*
    do
        if [[ ! -f $config ]]
        then
            continue;
        fi

        cp $config $dir
    done
    popd > /dev/null

    nitrogen-profile random

    pushd ~/.config/fastfetch/ > /dev/null

    for config in *.jsonc
    do
        if [[ ! -f $config ]] || [[ $config = "config.jsonc" ]]
        then
            continue;
        fi

        rm $config
    done
    popd > /dev/null

    pushd ~/.config/fastfetch_backup_/ > /dev/null
    dir="$HOME/.config/fastfetch/"

    if [[ ! -d $dir ]]
    then
        mkdir $dir > /dev/null
    fi

    for config in *.jsonc
    do
        if [[ ! -f $config ]]
        then
            continue;
        fi

        cp $config $dir
    done
    popd > /dev/null

    fastfetchconfig random > /dev/null

    rm ~/.bash_history > /dev/null

    clear
    fastfetch
}

LOCKDIR=/tmp/nitrogen_lock_directory/

if mkdir -- "$LOCKDIR"
then
    set_streamer_mode

    if rmdir -- "$LOCKDIR"
    then
        echo "successfully set streamer mode."
    else
        echo "could not remove lock." >&2
    fi
else
    echo "could not get lock." >&2
fi
