#!/bin/bash

if [[ ! "$(ls -A $HOME/.config/nitrogen_backup_/)" ]] && [[ ! "$(ls -A $HOME/.config/fastfetch_backup_/)" ]]
then
    echo -e "no need, already in streamer mode."
    exit 0;
fi

pushd ~/.config/nitrogen/ > /dev/null
dir="$HOME/.config/nitrogen_backup/"

if [[ ! -d $dir ]]
then
    mkdir $dir > /dev/null
fi

for config in profile*
do
    if [[ ! -f $config ]]
    then
        continue;
    fi

    mv $config $dir
done
popd > /dev/null

pushd ~/.config/nitrogen_backup_/ > /dev/null
dir="$HOME/.config/nitrogen/"

if [[ ! -d $dir ]]
then
    mkdir $dir > /dev/null
fi

for config in profile*
do
    if [[ ! -f $config ]]
    then
        continue;
    fi

    mv $config $dir
done
popd > /dev/null

nitrogen-profile random

pushd ~/.config/fastfetch/ > /dev/null
dir="$HOME/.config/fastfetch_backup/"

if [[ ! -d $dir ]]
then
    mkdir $dir > /dev/null
fi

for config in *.jsonc
do
    if [[ ! -f $config ]] || [[ $config = "config.jsonc" ]]
    then
        continue;
    fi

    mv $config $dir
done
popd > /dev/null

pushd ~/.config/fastfetch_backup_/ > /dev/null
dir="$HOME/.config/fastfetch/"

if [[ ! -d $dir ]]
then
    mkdir $dir > /dev/null
fi

for config in *.jsonc
do
    if [[ ! -f $config ]]
    then
        continue;
    fi

    mv $config $dir
done
popd > /dev/null

fastfetchconfig random > /dev/null

rm ~/.bash_history > /dev/null

clear
fastfetch
