#!/bin/bash

folders=("$HOME/repository/river2D/")
folders+=("$HOME/repository/marino/vendor/river2D/")
folders+=("$HOME/repository/islescape/vendor/river2D/")
folders+=("$HOME/repository/river2D_mapedit/vendor/river2D/")

folders+=("$HOME/repository/imgsurf/")
folders+=("$HOME/repository/river2D/vendor/imgsurf/")
folders+=("$HOME/repository/marino/vendor/river2D/vendor/imgsurf/")
folders+=("$HOME/repository/islescape/vendor/river2D/vendor/imgsurf/")
folders+=("$HOME/repository/river2D_mapedit/vendor/river2D/vendor/imgsurf/")

folders+=("$HOME/repository/puddle/")
folders+=("$HOME/repository/river2D/vendor/puddle/")
folders+=("$HOME/repository/islescape/vendor/puddle/")
folders+=("$HOME/repository/river2D_mapedit/vendor/puddle/")
folders+=("$HOME/repository/islescape/vendor/river2D/vendor/puddle/")
folders+=("$HOME/repository/river2D_mapedit/vendor/river2D/vendor/puddle/")

folders+=("$HOME/repository/marino/")
folders+=("$HOME/repository/dotfiles/")
folders+=("$HOME/repository/gitfluss/")
folders+=("$HOME/repository/blazeterm/")
folders+=("$HOME/repository/flushback/")
folders+=("$HOME/repository/river3D/")
folders+=("$HOME/repository/islescape/")
folders+=("$HOME/repository/river2D_mapedit")
folders+=("$HOME/repository/bash-collection/")

pushd $HOME/repository/ > /dev/null

function update()
{
    cd $1
    git fetch
    git pull
}

for folder in ${folders[@]}
do
    update $folder &
done

popd > /dev/null
