#!/bin/bash

folders=("$HOME/repository/puddle/")
folders+=("$HOME/repository/river2D/vendor/puddle/")
folders+=("$HOME/repository/river3D/vendor/puddle/")
folders+=("$HOME/repository/islescape/vendor/puddle/")
folders+=("$HOME/repository/river2D_mapedit/vendor/puddle/")
folders+=("$HOME/repository/islescape/vendor/river2D/vendor/puddle/")
folders+=("$HOME/repository/river2D_mapedit/vendor/river2D/vendor/puddle/")

folders+=("$HOME/repository/imgsurf/")
folders+=("$HOME/repository/river2D/vendor/imgsurf/")
folders+=("$HOME/repository/river3D/vendor/imgsurf/")
folders+=("$HOME/repository/marino/vendor/river2D/vendor/imgsurf/")
folders+=("$HOME/repository/islescape/vendor/river2D/vendor/imgsurf/")
folders+=("$HOME/repository/river2D_mapedit/vendor/river2D/vendor/imgsurf/")

folders+=("$HOME/repository/vertstream/")
folders+=("$HOME/repository/river3D/vendor/vertstream/")

folders+=("$HOME/repository/river3D/")

folders+=("$HOME/repository/river2D/")
folders+=("$HOME/repository/marino/vendor/river2D/")
folders+=("$HOME/repository/islescape/vendor/river2D/")
folders+=("$HOME/repository/river2D_mapedit/vendor/river2D/")

folders+=("$HOME/repository/marino/")
folders+=("$HOME/repository/dotfiles/")
folders+=("$HOME/repository/gitfluss/")
folders+=("$HOME/repository/blazeterm/")
folders+=("$HOME/repository/flushback/")
folders+=("$HOME/repository/river3D/")
folders+=("$HOME/repository/islescape/")
folders+=("$HOME/repository/river2D_mapedit")
folders+=("$HOME/repository/bash-collection/")

pushd $HOME/repository/ > /dev/null

PIDs=()

function update()
{
    if [[ ! -d $1 ]]
    then
        return;
    fi

    cd $1

    if [[ ! -d "./.git/" ]]
    then
        return;
    fi

    git fetch
    git pull
}

i=0

for folder in ${folders[@]}
do
    update $folder &
    PIDs[$i]=$!
    i=$((i + 1))
done

for pid in ${PIDs[*]}
do
    wait $pid
done

popd > /dev/null
