#!/bin/bash

maim -s /tmp/screenshot.png
xclip -selection clipboard -t image/png < /tmp/screenshot.png

magick /tmp/screenshot.png /tmp/screenshot.jpg

rm /tmp/screenshot.png
mv /tmp/screenshot.jpg ~/Pictures/screens/$(date +%s).jpg
