#!/bin/bash

read -p "ARE YOU SURE YOU WANT TO TURN OFF STREAMER MODE? (y/N): " -r

echo

if [[ $REPLY =~ ^[Yy]$ ]]
then
    pushd ~/.config/nitrogen_backup/ > /dev/null
    dir="$HOME/.config/nitrogen/"

    for config in profile*
    do
        if [[ ! -f $config ]]
        then
            continue;
        fi

        mv $config $dir
    done

    niconf=$(ls "$HOME/.config/nitrogen/" -I *clean.cfg -I *saved.cfg -I nitrogen.cfg | shuf -n 1)
    cp $dir/$niconf $dir/bg-saved.cfg
    nitrogen --restore 2> /dev/null

    pushd ~/.config/fastfetch_backup/ > /dev/null
    dir="$HOME/.config/fastfetch/"

    for config in *.jsonc
    do
        if [[ ! -f $config ]]
        then
            continue;
        fi

        mv $config $dir
    done

    ffconf=$(ls "$HOME/.config/fastfetch/" -I config.jsonc -I default.jsonc | shuf -n 1)

    cp $dir/$ffconf $dir/config.jsonc
    clear
    fastfetch

    popd > /dev/null
    popd > /dev/null

else
    exit 1
fi
