#!/bin/bash

function unset_streamer_mode()
{
    pushd ~/.config/nitrogen/ > /dev/null

    for config in profile*
    do
        if [[ ! -f $config ]]
        then
            continue;
        fi

        rm $config
    done
    popd > /dev/null

    pushd ~/.config/nitrogen_backup_/ > /dev/null
    dir="$HOME/.config/nitrogen/"

    for config in profile*
    do
        if [[ ! -f $config ]]
        then
            continue;
        fi

        cp $config $dir
    done

    nitrogen-profile random

    pushd ~/.config/fastfetch/ > /dev/null

    for config in *.jsonc
    do
        if [[ ! -f $config ]] || [[ $config = "config.jsonc" ]]
        then
            continue;
        fi

        rm $config
    done
    popd > /dev/null

    pushd ~/.config/fastfetch_backup_/ > /dev/null
    dir="$HOME/.config/fastfetch/"

    for config in *.jsonc
    do
        if [[ ! -f $config ]]
        then
            continue;
        fi

        cp $config $dir
    done

    fastfetchconfig random

    popd > /dev/null
}

LOCKDIR=/tmp/nitrogen_lock_directory/

if mkdir -- "$LOCKDIR"
then
    unset_streamer_mode

    if rmdir -- "$LOCKDIR"
    then
        echo "successfully unset streamer mode."
        echo "false" > $HOME/streamermode
    else
        echo "could not remove lock." >&2
    fi
else
    echo "could not get lock." >&2
fi
