#!/bin/bash

for archive in *zip
do
    echo -e "extracting $archive..."
    7z x -y "${archive}"

    if [[ $? != 0 ]]
    then
        echo -e "Error while extracting $archive."
    fi

    echo -e "removing source file: $archive\n"
    rm "${archive}"
done

for archive in *7z
do
    echo -e "extracting $archive..."
    7z x -y "${archive}"

    if [[ $? != 0 ]]
    then
        echo -e "Error while extracting $archive."
    fi

    echo -e "removing source file: $archive\n"
    rm "${archive}"
done

for archive in *rar
do
    echo -e "extracting $archive..."
    7z x -y "${archive}"

    if [[ $? != 0 ]]
    then
        echo -e "Error while extracting $archive."
    fi

    echo -e "removing source file: $archive\n"
    rm "${archive}"
done

for codes in *txt
do
    echo -e "removing text file: $codes\n"
    rm "${codes}"
done

# TODO: add gz and others
